version: "3.8"

x-airflow-common: &airflow-common
  image: airflow-pipeline:latest
  build: .
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    WAREHOUSE_HOST: warehouse-db
    WAREHOUSE_DB: warehouse
    WAREHOUSE_USER: ware
    WAREHOUSE_PASSWORD: ware
  volumes:
    - ./dags:/opt/airflow/dags
    - ./include:/opt/airflow/include
    - ./reports:/opt/airflow/reports
    - ./jars:/opt/airflow/jars
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - airflow-db
    - warehouse-db

services:
  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 10
    ports:
      - "5433:5432"

  warehouse-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ware
      POSTGRES_PASSWORD: ware
      POSTGRES_DB: warehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ware -d warehouse"]
      interval: 5s
      retries: 10
    ports:
      - "5434:5432"
    volumes:
      - ./include/sql/create_target_tables.sql:/docker-entrypoint-initdb.d/create_target_tables.sql:ro

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname A --lastname D --role Admin --email admin@example.com || true"

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8082:8080"
    depends_on:
      airflow-db:
        condition: service_healthy
      warehouse-db:
        condition: service_healthy

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-db:
        condition: service_healthy
      warehouse-db:
        condition: service_healthy
